# Generated by Django 4.2.3 on 2023-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_email_alter_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pass_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
